include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.drift.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/*.freezed.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
