name: manger
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared


  cupertino_icons: ^1.0.2
  freezed_annotation:  ^1.1.0
  riverpod: ^2.0.0-dev.0
  hooks_riverpod: ^2.0.0-dev.0
  flutter_hooks:
  flutter_riverpod: ^2.0.0-dev.0
  state_notifier: 0.7.2+1
  shared_preferences:
  auto_size_text:
  json_annotation:
  fluent_ui: ^3.10.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  auto_route: ^3.2.1
  dio:
  form_field_validator: ^1.1.0
  tuple: ^2.0.0
  font_awesome_flutter: ^10.1.0
  qr: ^3.0.1
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  qr_svg_generator: ^0.0.1
  file_picker: ^4.5.1
  path:
  flutter_staggered_grid_view: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable:
  auto_route_generator:
  build_runner:

scripts: script.yaml



flutter:


  uses-material-design: true

